version: '3.8'
services:
  formulario-app:
    image: ghcr.io/dsantos-sudo/formulario-nuevo-registro:latest
    container_name: formulario-contenedor
    restart: always
    ports:
      - "7000:7000"
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-formulario
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: --interval 300 --cleanup --label-enable --debug
